PracticeProject/Controllers/ResourcesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using X.PagedList;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PracticeProject.Areas.Identity.Data;
using PracticeProject.Models;
using System.Drawing.Printing;
using System.Linq.Dynamic.Core;
using Microsoft.Extensions.Configuration.UserSecrets;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.FileSystemGlobbing;
using Microsoft.Owin.Security.Provider;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore.Internal;
using LinqKit;

namespace PracticeProject.Controllers
{
    public class ResourcesController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly GoogleCaptchaService _googleCaptchaService;
        private readonly IHubContext<CommentHub> _commentHubContext;
        const int pageSizeComments = 8;
        const int pageSizeResources = 4;
        const int pageSizeRequests = 4;
        public ResourcesController(UserManager<User> userManager, ApplicationContext context, GoogleCaptchaService googleCaptchaService, IHubContext<CommentHub> commenthubContext, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _googleCaptchaService = googleCaptchaService;
            _commentHubContext = commenthubContext;
            _roleManager = roleManager;
        }
        [Authorize]
        public IActionResult ResourceRequest()
        {
            return View();
        }
        [Authorize]
        public async Task<IActionResult> SendRequest(string name, string link, string description, string token)
        {
            try
            {
                var captchaResult = await _googleCaptchaService.VerifyToken(token);
                if (!captchaResult)
                {
                    return Json(new { success = false, error = "Проблемы с каптчей" });
                }
                string userId = _userManager.GetUserId(User);
                ResourceRequestModel resourceRequest = new ResourceRequestModel(name, description, link, userId);
                await _context.ResourceRequests.AddAsync(resourceRequest);
                await _context.SaveChangesAsync();
                return Json(new { success = true });
            }
            catch (Exception ex) 
            {
                string errorMessage = "An error occurred while processing the chat request. Details: " + ex.Message;
                return Json(new { success = false, error = errorMessage });
            }
        }
        public async Task<IActionResult> ShowResourcesPage(int page = 1)
        {
            List<ResourceModel> resources = await GetResourcesFromDataSource(page);
            double resourcesAmount = await GetResourcesAmountFromDataSource();
            int totalPages = (int)Math.Ceiling(resourcesAmount / pageSizeResources);

            var viewModel = new ResourceViewModel<ResourceModel>
            {
                Resources = resources,
                CurrentPage = page,
                TotalPages = totalPages
            };

            return View(viewModel);
        }
        public async Task<IActionResult> ResourceById(int id)
        {
            var comments = await GetResourceCommentsFromDataSource(id);
            var resource = await _context.Resources.FindAsync(id);
            var viewModel = new ResourceByIdViewModel<CommentWithNicknameModel>
            {
                ResourceCommentsWithNickname = comments,
                Resource = resource
            };
            return View(viewModel);
        }
        public async Task<ResourceRequestsWithTotalPagesModel> GetRequestsFromDataSource(int page, bool watched = false, bool completed = false, bool rejected = false, bool nothing = false)
        {
            var predicate = PredicateBuilder.New<ResourceRequestWithNicknameModel>();
            if (watched)
                predicate = predicate.Or(x => x.Request.IsBeingWatched);
            if (completed)
                predicate = predicate.Or(x => x.Request.IsCompleted);
            if (rejected)
                predicate = predicate.Or(x => x.Request.IsRejected);
            if (nothing)
                predicate = predicate.Or(x => !x.Request.IsBeingWatched && !x.Request.IsCompleted && !x.Request.IsRejected);
            var result = (from request in _context.ResourceRequests
                          join user in _context.Users
                          on request.UserId equals user.Id
                          select new ResourceRequestWithNicknameModel
                          {
                              Request = request,
                              Nickname = user.Nickname,
                              CreatedAt = DateOnly.FromDateTime(request.CreatedAt)
                          })
                        .AsNoTracking()
                        .Where(predicate);

            if (!User.IsInRole("Admin"))
            {
                string userId = _userManager.GetUserId(User);
                result = result.Where(request => request.Request.UserId == userId);
            }

            double amount = await result.CountAsync();
            int totalPages = (int)Math.Ceiling(amount / pageSizeRequests);
            if (totalPages < 1) totalPages = 1;
            result = result.Skip((page - 1) * pageSizeRequests).Take(pageSizeRequests);

            ResourceRequestsWithTotalPagesModel newResult = new ResourceRequestsWithTotalPagesModel()
            {
                Requests = result,
                TotalPages = totalPages
            };
            return newResult;
        }
        public async Task<IActionResult> ShowRequestsPage(int page = 1)
        {
            bool watched = Request.Query.ContainsKey("watched");
            bool completed = Request.Query.ContainsKey("completed");
            bool rejected = Request.Query.ContainsKey("rejected");
            bool nothing = Request.Query.ContainsKey("nothing");
            ResourceRequestsWithTotalPagesModel requestsWithTotalPages = await GetRequestsFromDataSource(page, watched, completed, rejected, nothing);
            var requests = requestsWithTotalPages.Requests;
            var viewModel = new ResourceViewModel<ResourceRequestWithNicknameModel>
            {
                Resources = requests,
                CurrentPage = page,
                TotalPages = requestsWithTotalPages.TotalPages
            };

            return View(viewModel);
        }
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> MakeRequestWatched(int id)
        {
            try
            {
                ResourceRequestModel request = await _context.ResourceRequests.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
                if (request.IsBeingWatched || request.IsCompleted || request.IsRejected) return StatusCode(409);
                request.IsBeingWatched = true;
                _context.Update(request);
                await _context.SaveChangesAsync();
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                string errorMessage = "An error occurred while processing the chat request. Details1: " + ex.Message;
                return Json(new { success = false, error = errorMessage });
            }
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CancelRequest(int id)
        {
            try
            {
                ResourceRequestModel request = await _context.ResourceRequests.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
                if (request.IsCompleted || request.IsRejected) return StatusCode(409);
                request.IsRejected = true;
                request.IsBeingWatched = false;
                _context.Update(request);
                await _context.SaveChangesAsync();
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                string errorMessage = "An error occurred while processing the chat request. Details1: " + ex.Message;
                return Json(new { success = false, error = errorMessage });
            }
        }
        public async Task<List<ResourceModel>> GetResourcesFromDataSource(int page)
        {
            return await _context.Resources.Skip((page - 1) * pageSizeResources).Take(pageSizeResources).ToListAsync();
        }
        public async Task<int> GetRequestsAmountFromDataSource()
        {
            return await _context.ResourceRequests.CountAsync();
        }
        public async Task<int> GetResourcesAmountFromDataSource()
        {
            return await _context.Resources.CountAsync();
        }
        public async Task<List<CommentWithNicknameModel>> GetResourceCommentsFromDataSource(int id, int page = 1)
        {
            return await (from comment in _context.Comments
                                join user in _context.Users
                                on comment.UserId equals user.Id
                                where comment.ResourceId == id
                                select new CommentWithNicknameModel
                                {
                                    CommentText = comment.Text,
                                    Nickname = user.Nickname,
                                    CreatedAt = DateOnly.FromDateTime(comment.CreatedAt)
                                })
                                .AsNoTracking()
                                .Skip((page - 1) * pageSizeComments)
                                .Take(pageSizeComments)
                                .ToListAsync();
        }
        public async Task<int> GetResourceCommentsAmountFromDataSource(int id)
        {

PracticeProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Hunt </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticeProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid container">
                <div><a class="navbar-brand" asp-area="" asp-controller="Resources" asp-action="ShowResourcesPage"><img class="logo-flague" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Wapen_Ossetien.svg/2048px-Wapen_Ossetien.svg.png" /></a></div>
                <div><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("ShowResourcesPage", "Resources", new { area = "" })">
                                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Выйти</button>
                                </form>
                            </li>
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-controller="ResourceModels" asp-action="Index">Админ-панель</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Resources" asp-action="ShowRequestsPage" asp-route-watched="true" asp-route-nothing="true">Заявки</a>
                                </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Регистрация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Войти</a>
                            </li>
                        }
                    </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 resource-sec">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">CryTek &copy; 2023
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>